// Datos de prueba (mock) — reemplazar por datos reales de la API más adelante.

export const mockProducts = [
  {
    id: 1,
    sku: "BRK-1042",
    name: "Pastillas de freno cerámicas",
    brand: "Toyota",
    model: "Corolla",
    year: 2018,
    price: 45.99,
    stock: 4,
    minStock: 10,
    category: "Frenos",
    image: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=600&q=80",
    description:
      "Juego de pastillas de freno cerámicas de alto rendimiento, baja generación de polvo y frenado silencioso.",
  },
  {
    id: 2,
    sku: "FLT-2231",
    name: "Filtro de aceite premium",
    brand: "Honda",
    model: "Civic",
    year: 2020,
    price: 12.5,
    stock: 32,
    minStock: 15,
    category: "Filtros",
    image: "https://images.unsplash.com/photo-1635073908681-b4dfd6c4b56b?w=600&q=80",
    description: "Filtro de aceite de alta capacidad de filtrado, compatible con motores de 1.5L y 2.0L.",
  },
  {
    id: 3,
    sku: "BAT-8890",
    name: "Batería 12V 60Ah",
    brand: "Volkswagen",
    model: "Golf",
    year: 2019,
    price: 129.0,
    stock: 8,
    minStock: 5,
    category: "Eléctrico",
    image: "https://images.unsplash.com/photo-1620714223084-8fcacc6dfd8d?w=600&q=80",
    description: "Batería libre de mantenimiento con tecnología de calcio, 60Ah y 540A de arranque en frío.",
  },
  {
    id: 4,
    sku: "SPK-3320",
    name: "Bujías de iridio (x4)",
    brand: "Ford",
    model: "Focus",
    year: 2017,
    price: 38.75,
    stock: 2,
    minStock: 8,
    category: "Encendido",
    image: "https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=600&q=80",
    description: "Set de 4 bujías de iridio para una combustión más eficiente y mayor vida útil.",
  },
  {
    id: 5,
    sku: "SHK-5567",
    name: "Amortiguador delantero",
    brand: "Chevrolet",
    model: "Cruze",
    year: 2016,
    price: 89.9,
    stock: 14,
    minStock: 6,
    category: "Suspensión",
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600&q=80",
    description: "Amortiguador hidráulico de gas, mejora la estabilidad y el confort de manejo.",
  },
  {
    id: 6,
    sku: "ALT-7712",
    name: "Alternador 90A",
    brand: "Nissan",
    model: "Sentra",
    year: 2021,
    price: 156.0,
    stock: 1,
    minStock: 4,
    category: "Eléctrico",
    image: "https://images.unsplash.com/photo-1597766353939-da3a40f7903c?w=600&q=80",
    description: "Alternador remanufacturado de 90 amperios con garantía de 12 meses.",
  },
  {
    id: 7,
    sku: "RAD-2098",
    name: "Radiador de aluminio",
    brand: "Toyota",
    model: "Hilux",
    year: 2022,
    price: 198.5,
    stock: 9,
    minStock: 5,
    category: "Refrigeración",
    image: "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=600&q=80",
    description: "Radiador de aluminio de doble núcleo, mayor disipación de calor para uso severo.",
  },
  {
    id: 8,
    sku: "BLT-1183",
    name: "Correa de distribución",
    brand: "Honda",
    model: "CR-V",
    year: 2019,
    price: 28.4,
    stock: 21,
    minStock: 10,
    category: "Motor",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    description: "Correa de distribución reforzada con fibra, alta resistencia a la temperatura.",
  },
]

export const mockSales = [
  {
    id: "V-1001",
    date: "2026-06-20",
    product: "Pastillas de freno cerámicas",
    quantity: 2,
    total: 91.98,
    customer: "client",
  },
  {
    id: "V-1002",
    date: "2026-06-21",
    product: "Filtro de aceite premium",
    quantity: 5,
    total: 62.5,
    customer: "client",
  },
  {
    id: "V-1003",
    date: "2026-06-22",
    product: "Batería 12V 60Ah",
    quantity: 1,
    total: 129.0,
    customer: "otro_cliente",
  },
  {
    id: "V-1004",
    date: "2026-06-23",
    product: "Bujías de iridio (x4)",
    quantity: 3,
    total: 116.25,
    customer: "client",
  },
  {
    id: "V-1005",
    date: "2026-06-24",
    product: "Amortiguador delantero",
    quantity: 2,
    total: 179.8,
    customer: "otro_cliente",
  },
]

export const mockUsers = [
  { id: 1, name: "Ana Admin", email: "admin@autopart.com", role: "admin", status: "activo" },
  { id: 2, name: "Eduardo Empleado", email: "empleado@autopart.com", role: "employee", status: "activo" },
  { id: 3, name: "Carla Cliente", email: "cliente@autopart.com", role: "client", status: "activo" },
  { id: 4, name: "Mario Méndez", email: "mario@autopart.com", role: "employee", status: "inactivo" },
]

export const brands = ["Toyota", "Honda", "Volkswagen", "Ford", "Chevrolet", "Nissan"]
export const years = [2016, 2017, 2018, 2019, 2020, 2021, 2022]
